export interface Medida{
    Name: string,
    Short: string,
}

export interface CustomIcon {
    Display: string,
    Source: string,
}
export const foodIcons: CustomIcon[] = [
    {Display: '?', Source: 'help'},
    {Display: 'Aceituna', Source: 'food-aceituna'},
    {Display: 'Agua', Source: 'food-agua'},
    {Display: 'Ajo', Source: 'food-ajo'},
    {Display: 'Alcohol', Source: 'food-alcohol'},
    {Display: 'Arroz', Source: 'food-arroz'},
    {Display: 'Azucar', Source: 'food-azucar'},
    {Display: 'Berenjena', Source: 'food-berenjena'},
    {Display: 'Brocoli', Source: 'food-brocoli'},
    {Display: 'Calabaza', Source: 'food-calabaza'},
    {Display: 'Canela', Source: 'food-canela'},
    {Display: 'Carne', Source: 'food-carne'},
    {Display: 'Cebolla (blanca)', Source: 'food-cebolla-blanca'},
    {Display: 'Cebolla (morada)', Source: 'food-cebolla-morada'},
    {Display: 'Cereza', Source: 'food-cereza'},
    {Display: 'Chile (rojo)', Source: 'food-chile-rojo'},
    {Display: 'Chile (verde)', Source: 'food-chile-verde'},
    {Display: 'Chocolate', Source: 'food-chocolate'},
    {Display: 'Chorizo', Source: 'food-chorizo'},
    {Display: 'Crema', Source: 'food-crema'},
    {Display: 'Especia en polvo', Source: 'food-especia-polvo'},
    {Display: 'Especia', Source: 'food-especia'},
    {Display: 'Fresa', Source: 'food-fresa'},
    {Display: 'Hoja', Source: 'food-hoja'},
    {Display: 'Hongo', Source: 'food-hongo'},
    {Display: 'Huevo', Source: 'food-huevo'},
    {Display: 'Jamón', Source: 'food-jamon'},
    {Display: 'Laurel', Source: 'food-laurel'},
    {Display: 'Leche', Source: 'food-leche'},
    {Display: 'Limón', Source: 'food-limon'},
    {Display: 'Líquido', Source: 'food-liquido'},
    {Display: 'Maíz', Source: 'food-maiz'},
    {Display: 'Mantequilla', Source: 'food-mantequilla'},
    {Display: 'Manzana', Source: 'food-manzana'},
    {Display: 'Masa', Source: 'food-masa'},
    {Display: 'Naranja', Source: 'food-naranja'},
    {Display: 'Oregano', Source: 'food-oregano'},
    {Display: 'Pan', Source: 'food-pan'},
    {Display: 'Papa', Source: 'food-papa'},
    {Display: 'Pasta', Source: 'food-pasta'},
    {Display: 'Peperoni', Source: 'food-peperoni'},
    {Display: 'Pescado', Source: 'food-pez'},
    {Display: 'Piloncillo', Source: 'food-piloncillo'},
    {Display: 'Pimiento', Source: 'food-pimiento'},
    {Display: 'Plátano', Source: 'food-platano'},
    {Display: 'Pollo', Source: 'food-pollo'},
    {Display: 'Polvo (saco)', Source: 'food-polvo'},
    {Display: 'Pure de tomate', Source: 'food-pure-tomate'},
    {Display: 'Queso', Source: 'food-queso'},
    {Display: 'Rábano', Source: 'food-rabano'},
    {Display: 'Sal', Source: 'food-sal'},
    {Display: 'Salsa', Source: 'food-salsa'},
    {Display: 'Salchicha', Source: 'food-salchicha'},
    {Display: 'Sandía', Source: 'food-sandia'},
    {Display: 'Tocino', Source: 'food-tocino'},
    {Display: 'Tomate', Source: 'food-tomate'},
    {Display: 'Uva', Source: 'food-uva'},
    {Display: 'Zanahoria', Source: 'food-zanahoria'},
];

export const kitchenIcons: CustomIcon[] = [
    {Display: '?', Source: 'help'},
    {Display: 'Cazuela', Source: 'kitchen-cazuela'},
    {Display: 'Freidora', Source: 'kitchen-freidora'},
    {Display: 'Horno', Source: 'kitchen-horno'},
    {Display: 'Licuadora', Source: 'kitchen-licuadora'},
    {Display: 'Mezclador', Source: 'kitchen-mezclador'},
    {Display: 'Microondas', Source: 'kitchen-microondas'},
    {Display: 'Molcajete', Source: 'kitchen-molcajete'},
    {Display: 'Olla', Source: 'kitchen-olla'},
    {Display: 'Parrilla', Source: 'kitchen-parrilla'},
    {Display: 'Refrigerador', Source: 'kitchen-refrigerador'},
    {Display: 'Sarten', Source: 'kitchen-sarten'},
];

export const Medidas: Medida[] = [
    {Name: 'Unidades', Short: ''},
    {Name: 'Miligramos', Short: 'mg'},
    {Name: 'Gramos', Short: 'gr'},
    {Name: 'Kilogramos', Short: 'kg'},
    {Name: 'Mililitros', Short: 'ml'},
    {Name: 'Litros', Short: 'L'},
    {Name: 'Tazas', Short: ' taza(s)'},
    {Name: 'Cucharadas', Short: ' cucharada(s)'},
];

export const Dificultades: string[] = [
    'Principiante',
    'Fácil',
    'Intermedio',
    'Difícil',
    'Avanzado',
    'Experto',
];

export const DifficultyColors: string[] = [
    '#00BCD4',
    '#4CAF50',
    '#8BC34A',
    '#D0E000',
    '#FF9800',
    '#FF5722',
    '#DF1A1A',
    '#FF0000',    
];